### ISSUE TITLE
Support multiple docroots

### ISSUE THREAD

**Issue by steffendietz** [maglnet/MaglLegacyApplication#2]
Sometimes it could be helpful to support more than just one legacy document root.

To maintain backwards compatibility, the `doc_root` option could accept both, a string value or an array of strings.

**Comment by maglnet** [comment]
+1, I'll check this in the next days.

**Comment by maglnet** [comment]
@steffendietz could you please check if this fits our needs?

**Comment by steffendietz** [comment]
Will check this tomorrow. Thanks for your quick response. :+1:
